### ISSUE TITLE
This extension can support Tensorflow 1.15?

### ISSUE THREAD

**Issue by sunhailin-Leo** [NVIDIA/atex#1]

**Comment by nluehr** [comment]
TensorFlow 1.x releases are not supported at this time.

**Comment by sunhailin-Leo** [comment]
> TensorFlow 1.x releases are not supported at this time.

Have any roadmap or never supported it? 🤔

**Comment by nluehr** [comment]
Currently we are focused on further improving kernel performance and have not considered extending support to TF 1.x. You are welcome to contribute a TF 1.x PR if you would like.
